apiVersion: v1
kind: Service
metadata:
  name: elephant-boardroom-service
  namespace: elephant-boardroom
  labels:
    app: elephant-boardroom
spec:
  type: ClusterIP
  selector:
    app: elephant-boardroom
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
